In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("/content/Feature engineering _ dataset.csv")

In [4]:
df = df.copy()

In [5]:
print("Shape:", df.shape)

Shape: (512, 15)

In [6]:
print(df.head(10))

  Employee_ID             Name       Age  Gender     City    Department  \
0     EMP1339      Ravi Saxena        56    Male   Mumbai  Data Science
1     EMP1040  Sanjay Malhotra        40    Male    DELHI         Sales
2     EMP1186    Kiran Trivedi        53    Male  Kolkata  Data Science
3     EMP1476       Priya Shah  48 years  Female     Pune            HR
4     EMP1030       Suresh Rao        28  Female   Jaipur     Marketing
5     EMP1173      Sneha Verma        42  Female  Chennai         Sales
6     EMP1050      Ravi Sharma        41  Female    Surat         Sales
7     EMP1118       Vivek Shah        56    Male     Pune  Data Science
8     EMP1188     Vivek Mishra        48       F   Jaipur    Operations
9     EMP1386       Ravi Mehta        37       M   Jaipur        Design

     Education Experience_Years         Salary Performance_Score  \
0      Diploma               31         163755                83
1     Master's               16          97043                68
2     Master's               30         156862                75
3   Bachelor's               23  133665 rupees                68
4   Bachelor's                3          35848               94%
5          PhD               18          98959                65
6     Master's               17         106388                81
7      Diploma               33         166434                68
8  High School               23         123270                89
9     Master's               15          85992                43

  Performance_Rating   Join_Date                       Email         Phone  \
0               Good  2017-08-31     ravi.saxena97@gmail.com  9.794577e+09
1               Good  2022-09-26  sanjay.malhotra66gmail.com  9.570596e+09
2          Excellent  2019-01-09   kiran.trivedi43@gmail.com  9.522802e+09
3            Average     invalid      priya.shah61@gmail.com  9.563370e+09
4               Good  2021-03-28       suresh.rao57gmail.com  9.149369e+09
5            Average  2016-04-03     SNEHA.VERMA83@GMAIL.COM  9.818985e+09
6            Average  2020-08-27     ravi.sharma69@gmail.com  9.431527e+09
7          Excellent  2019-08-16      vivek.shah43@gmail.com  9.240083e+09
8          Excellent  2020-10-20                         NaN  9.155626e+09
9          Excellent  2016-07-14      ravi.mehta99@gmail.com  9.462456e+09

  Loan_Approved
0           Yes
1            No
2           Yes
3            No
4           Yes
5            No
6            No
7           Yes
8            No
9            No

In [7]:
print(df.dtypes)

Employee_ID            object
Name                   object
Age                    object
Gender                 object
City                   object
Department             object
Education              object
Experience_Years       object
Salary                 object
Performance_Score      object
Performance_Rating     object
Join_Date              object
Email                  object
Phone                 float64
Loan_Approved          object
dtype: object

In [8]:
print(df.isnull().sum())

Employee_ID            0
Name                   0
Age                   44
Gender                20
City                  11
Department             6
Education             20
Experience_Years      15
Salary                15
Performance_Score     30
Performance_Rating    18
Join_Date              0
Email                 17
Phone                 21
Loan_Approved         19
dtype: int64

In [9]:
print((df.isnull().sum() / len(df) * 100).round(2))

Employee_ID           0.00
Name                  0.00
Age                   8.59
Gender                3.91
City                  2.15
Department            1.17
Education             3.91
Experience_Years      2.93
Salary                2.93
Performance_Score     5.86
Performance_Rating    3.52
Join_Date             0.00
Email                 3.32
Phone                 4.10
Loan_Approved         3.71
dtype: float64

In [10]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 12

In [11]:
print(df[df.duplicated()])

    Employee_ID            Name Age  Gender       City   Department  \
159     EMP1234    Manish Gupta  43    Male       Pune      Support
194     EMP1357      Meera Nair  50  Female     Mumbai  Engineering
242     EMP1230   Suresh Chopra  40    Male  HYDERABAD  Engineering
248     EMP1421     Kiran Gupta  53    Male       Pune        Legal
267     EMP1273      Ravi Mehta  44  Female  Hyderabad      Finance
340     EMP1203   Ranjit Mishra  26    male  Bangalore           HR
342     EMP1223    Shreya Joshi  31  Female  HYDERABAD    Marketing
348     EMP1030      Suresh Rao  28  Female     Jaipur    Marketing
395     EMP1387     Nisha Patel  39    Male     Jaipur        Legal
412     EMP1031    Rajesh Joshi  42  Female      Surat      Support
428     EMP1083    Seema Pandey  33    Male    Kolkata   Operations
494     EMP1221  Lakshmi Pandey  58    Male     Mumbai      Finance

       Education Experience_Years         Salary Performance_Score  \
159      Diploma               19         108307               NaN
194      Diploma               25         145815               100
242      Diploma               15          89625                99
248     Master's               29         163238            8000.0
267   Bachelor's               19  116186 rupees                82
340   Bachelor's                3          45950                64
342  High School                7          65363                46
348   Bachelor's                3          35848               94%
395  High School               15         100599                82
412  High School               20         110098               NaN
428   Bachelor's              NaN          52462                56
494  High School           35 yrs         185218                67

    Performance_Rating   Join_Date                       Email         Phone  \
159          Excellent  2021-07-21    manish.gupta59@gmail.com  9.112911e+09
194            Average  2017-08-06      meera.nair16@gmail.com  9.451958e+09
242                NaN  2020-10-12   suresh.chopra14@gmail.com  9.797051e+09
248               Good  2021-08-06     kiran.gupta64@gmail.com  9.559428e+09
267               Good  2015-11-11      ravi.mehta19@gmail.com  9.483754e+09
340               Good  2021-09-21   ranjit.mishra64@gmail.com  9.309938e+09
342            Average  2019-10-16    shreya.joshi96@gmail.com  9.201572e+09
348               Good  2021-03-28       suresh.rao57gmail.com  9.149369e+09
395          Excellent  2019-07-12     nisha.patel15@gmail.com  9.461540e+09
412          Excellent  2015-12-01                         NaN  9.767976e+09
428            Average  2017-12-14    seema.pandey38@gmail.com  9.490212e+09
494               Good  2019-02-04  lakshmi.pandey96@gmail.com  9.289932e+09

    Loan_Approved
159            No
194           Yes
242            No
248            No
267            No
340           Yes
342           Yes
348           Yes
395           NaN
412            No
428           Yes
494           Yes

In [12]:
df = df.drop_duplicates()

In [13]:
print("Shape after removing duplicates:", df.shape)

Shape after removing duplicates: (500, 15)

In [14]:
print(df['Gender'].unique())

['Male' 'Female' 'F' 'M' 'female' '0' 'FEMALE' 'male' nan '1' 'MALE']

In [15]:
def clean_gender(val):
    if str(val).strip().lower() in ['male', 'm', '1']:
        return 'Male'
    elif str(val).strip().lower() in ['female', 'f', '0']:
        return 'Female'
    else:
        return np.nan

In [16]:
df['Gender_Clean'] = df['Gender'].apply(clean_gender)

In [17]:
df['Gender_Clean']

0        Male
1        Male
2        Male
3      Female
4      Female
        ...
507    Female
508      Male
509      Male
510    Female
511      Male
Name: Gender_Clean, Length: 500, dtype: object

In [18]:
print(df['Gender_Clean'].unique())

['Male' 'Female' nan]

In [19]:
df['Salary_Clean'] = df['Salary'].astype(str)
df['Salary_Clean'] = df['Salary_Clean'].str.replace('rupees','', regex=False)
df['Salary_Clean'] = df['Salary_Clean'].str.replace('k','000', regex=False)
df['Salary_Clean'] = df['Salary_Clean'].str.replace(',','', regex=False)
df['Salary_Clean'] = pd.to_numeric(df['Salary_Clean'], errors='coerce')

In [20]:
df['Salary_Clean']

0      163755.0
1       97043.0
2      156862.0
3      133665.0
4       35848.0
         ...
507     31616.0
508     29004.0
509    137690.0
510    124763.0
511     48108.0
Name: Salary_Clean, Length: 500, dtype: float64

In [21]:
df['Age_Clean'] = df['Age'].astype(str).str.replace(' years','')
df['Age_Clean'] = pd.to_numeric(df['Age_Clean'], errors='coerce')

In [22]:
df.loc[(df['Age_Clean'] < 18) | (df['Age_Clean'] > 80), 'Age_Clean'] = np.nan

In [23]:
df['Age_Clean']

0      56.0
1      40.0
2      53.0
3      48.0
4      28.0
       ...
507    22.0
508    26.0
509    48.0
510    47.0
511    28.0
Name: Age_Clean, Length: 500, dtype: float64

In [24]:
df['Experience_Clean'] = df['Experience_Years'].astype(str)
df['Experience_Clean'] = df['Experience_Clean'].str.replace(' yrs','')
df['Experience_Clean'] = df['Experience_Clean'].replace('fresher', '0')
df['Experience_Clean'] = pd.to_numeric(df['Experience_Clean'], errors='coerce')

In [25]:
df['Experience_Clean']

0      31.0
1      16.0
2      30.0
3      23.0
4       3.0
       ...
507     0.0
508     2.0
509    24.0
510    22.0
511     6.0
Name: Experience_Clean, Length: 500, dtype: float64

In [26]:
print("Null before:", df['Age_Clean'].isnull().sum())

df['Age_Clean'].fillna(df['Age_Clean'].mean(), inplace=True)

print("Null after:", df['Age_Clean'].isnull().sum())

Null before: 58
Null after: 0

/tmp/ipykernel_928/4015667836.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age_Clean'].fillna(df['Age_Clean'].mean(), inplace=True)

In [27]:
df['Salary_Clean'].fillna(df['Salary_Clean'].median(), inplace=True)
df['Experience_Clean'].fillna(df['Experience_Clean'].median(), inplace=True)

/tmp/ipykernel_928/1814566929.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Salary_Clean'].fillna(df['Salary_Clean'].median(), inplace=True)

In [28]:
df['Age_Clean']

0      56.0
1      40.0
2      53.0
3      48.0
4      28.0
       ...
507    22.0
508    26.0
509    48.0
510    47.0
511    28.0
Name: Age_Clean, Length: 500, dtype: float64

In [29]:
df['Salary_Clean']

0      163755.0
1       97043.0
2      156862.0
3      133665.0
4       35848.0
         ...
507     31616.0
508     29004.0
509    137690.0
510    124763.0
511     48108.0
Name: Salary_Clean, Length: 500, dtype: float64

In [30]:
df['Experience_Clean']

0      31.0
1      16.0
2      30.0
3      23.0
4       3.0
       ...
507     0.0
508     2.0
509    24.0
510    22.0
511     6.0
Name: Experience_Clean, Length: 500, dtype: float64

In [31]:
cat_cols = ['Gender_Clean','City','Department','Education','Performance_Rating']

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

/tmp/ipykernel_928/1411526224.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode()[0], inplace=True)

In [32]:
print(df.columns)

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Education', 'Experience_Years', 'Salary', 'Performance_Score',
       'Performance_Rating', 'Join_Date', 'Email', 'Phone', 'Loan_Approved',
       'Gender_Clean', 'Salary_Clean', 'Age_Clean', 'Experience_Clean'],
      dtype='object')

In [33]:
df.columns = df.columns.str.strip().str.replace(" ", "_")
print(df.columns)

Index(['Employee_ID', 'Name', 'Age', 'Gender', 'City', 'Department',
       'Education', 'Experience_Years', 'Salary', 'Performance_Score',
       'Performance_Rating', 'Join_Date', 'Email', 'Phone', 'Loan_Approved',
       'Gender_Clean', 'Salary_Clean', 'Age_Clean', 'Experience_Clean'],
      dtype='object')

In [35]:
df['Score_Clean'] = df['Performance_Score'].astype(str).str.replace('%','')
df['Score_Clean'] = pd.to_numeric(df['Score_Clean'], errors='coerce')

In [36]:
df.loc[(df['Score_Clean'] < 0) | (df['Score_Clean'] > 100), 'Score_Clean'] = np.nan

In [37]:
print(df[['Performance_Score','Score_Clean']].head())

  Performance_Score  Score_Clean
0                83         83.0
1                68         68.0
2                75         75.0
3                68         68.0
4               94%         94.0

In [39]:
df['Loan_Approved'] = df['Loan_Approved'].fillna(method='ffill')
df['Loan_Approved'] = df['Loan_Approved'].fillna(method='bfill')

/tmp/ipykernel_928/3714369959.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Loan_Approved'] = df['Loan_Approved'].fillna(method='ffill')
/tmp/ipykernel_928/3714369959.py:2: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Loan_Approved'] = df['Loan_Approved'].fillna(method='bfill')

In [40]:
print(df['Loan_Approved'].isnull().sum())

0

In [41]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['Gender_Encoded'] = le.fit_transform(df['Gender_Clean'])

print(dict(zip(le.classes_, le.transform(le.classes_))))
print(df['Gender_Encoded'].value_counts())

{'Female': np.int64(0), 'Male': np.int64(1)}
Gender_Encoded
1    290
0    210
Name: count, dtype: int64

In [42]:
df['Loan_Encoded'] = df['Loan_Approved'].map({'Yes':1, 'No':0})
print(df[['Loan_Approved','Loan_Encoded']].head(10))

  Loan_Approved  Loan_Encoded
0           Yes             1
1            No             0
2           Yes             1
3            No             0
4           Yes             1
5            No             0
6            No             0
7           Yes             1
8            No             0
9            No             0

In [43]:
dept_dummies = pd.get_dummies(df['Department'], prefix='Dept')

print("Before shape:", df.shape)

df = pd.concat([df, dept_dummies], axis=1)
df.drop('Department', axis=1, inplace=True)

print("After shape:", df.shape)
print(dept_dummies.columns)

Before shape: (500, 22)
After shape: (500, 31)
Index(['Dept_Data Science', 'Dept_Design', 'Dept_Engineering', 'Dept_Finance',
       'Dept_HR', 'Dept_Legal', 'Dept_Marketing', 'Dept_Operations',
       'Dept_Sales', 'Dept_Support'],
      dtype='object')

In [44]:
df['City'] = df['City'].str.strip().str.title()

city_dummies = pd.get_dummies(df['City'], prefix='City', drop_first=True)
df = pd.concat([df, city_dummies], axis=1)
df.drop('City', axis=1, inplace=True)

print("New city columns:", len(city_dummies.columns))

New city columns: 9

In [45]:
from sklearn.preprocessing import OrdinalEncoder

edu_order = ['High School','Diploma',"Bachelor's","Master's",'PhD']

oe = OrdinalEncoder(categories=[edu_order])
df['Education_Encoded'] = oe.fit_transform(df[['Education']]) + 1

print(pd.crosstab(df['Education'], df['Education_Encoded']))

Education_Encoded  1.0  2.0  3.0  4.0  5.0
Education
Bachelor's           0    0   89    0    0
Diploma              0   99    0    0    0
High School         90    0    0    0    0
Master's             0    0    0   93    0
PhD                  0    0    0    0  129

In [46]:
rating_map = {
    'Poor':1,
    'Average':2,
    'Good':3,
    'Excellent':4
}

df['Rating_Encoded'] = df['Performance_Rating'].map(rating_map)

print(pd.crosstab(df['Performance_Rating'], df['Rating_Encoded']))

Rating_Encoded       1    2    3    4
Performance_Rating
Average              0  129    0    0
Excellent            0    0    0  120
Good                 0    0  200    0
Poor                51    0    0    0

In [47]:
Q1 = df['Salary_Clean'].quantile(0.25)
Q3 = df['Salary_Clean'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Outliers below:", (df['Salary_Clean'] < lower).sum())
print("Outliers above:", (df['Salary_Clean'] > upper).sum())

# Capping
df['Salary_Capped'] = np.where(df['Salary_Clean'] < lower, lower,
                       np.where(df['Salary_Clean'] > upper, upper,
                                df['Salary_Clean']))

print(df['Salary_Capped'].min(), df['Salary_Capped'].max())

Outliers below: 0
Outliers above: 9
15592.0 265219.25

In [48]:
# Join date
df['Join_Date'] = pd.to_datetime(df['Join_Date'], errors='coerce')
df['Join_Date'].fillna(df['Join_Date'].median(), inplace=True)

today = pd.Timestamp.today()

df['Tenure_Years'] = ((today - df['Join_Date']).dt.days / 365).round(1)
df['Join_Year'] = df['Join_Date'].dt.year
df['Join_Quarter'] = df['Join_Date'].dt.quarter

/tmp/ipykernel_928/765421888.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Join_Date'].fillna(df['Join_Date'].median(), inplace=True)

In [51]:
df['Join_Quarter']

0      3
1      3
2      1
3      1
4      1
      ..
507    4
508    4
509    4
510    4
511    4
Name: Join_Quarter, Length: 500, dtype: int32

In [50]:
df['Join_Year']

0      2017
1      2022
2      2019
3      2019
4      2021
       ...
507    2018
508    2015
509    2016
510    2022
511    2022
Name: Join_Year, Length: 500, dtype: int32

In [49]:
df['Tenure_Years']

0       8.6
1       3.5
2       7.2
3       7.1
4       5.0
       ...
507     7.4
508    10.4
509     9.4
510     3.3
511     3.2
Name: Tenure_Years, Length: 500, dtype: float64

In [52]:
df['Salary_Per_Year_Exp'] = (df['Salary_Capped'] / (df['Experience_Clean'] + 1)).round(2)

df['Score_Salary_Ratio'] = (df['Score_Clean'] / df['Salary_Capped'] * 1000).round(4)

df['Is_Senior'] = np.where(df['Age_Clean'] >= 40, 1, 0)

df['Exp_Age_Ratio'] = (df['Experience_Clean'] / df['Age_Clean']).round(3)

print(df[['Salary_Per_Year_Exp','Score_Salary_Ratio','Is_Senior','Exp_Age_Ratio']].describe())

       Salary_Per_Year_Exp  Score_Salary_Ratio   Is_Senior  Exp_Age_Ratio
count           500.000000          439.000000  500.000000     500.000000
mean           9617.573700            1.015409    0.440000       0.361212
std           16062.071971            0.833993    0.496884       0.199951
min            2261.000000            0.173400    0.000000       0.000000
25%            5231.907500            0.500650    0.000000       0.200000
50%            5774.620000            0.719600    0.000000       0.392500
75%            7560.425000            1.213900    1.000000       0.528250
max          265219.250000            5.579800    1.000000       0.900000

In [53]:
bins = [18,30,42,54,80]
labels = ['Young','Mid-Career','Senior','Veteran']

df['Age_Group'] = pd.cut(df['Age_Clean'], bins=bins, labels=labels)

age_map = {'Young':1,'Mid-Career':2,'Senior':3,'Veteran':4}
df['Age_Group_Encoded'] = df['Age_Group'].map(age_map)

print(df['Age_Group'].value_counts())

Age_Group
Mid-Career    189
Senior        137
Young         117
Veteran        57
Name: count, dtype: int64

In [54]:
df['Salary_Bracket'] = pd.qcut(df['Salary_Capped'], 4,
                               labels=['Low','Lower-Mid','Upper-Mid','High'])

print(df['Salary_Bracket'].value_counts())
print(pd.crosstab(df['Salary_Bracket'], df['Loan_Approved']))

Salary_Bracket
Lower-Mid    142
Low          125
High         125
Upper-Mid    108
Name: count, dtype: int64
Loan_Approved   No  Yes
Salary_Bracket
Low             53   72
Lower-Mid       72   70
Upper-Mid       53   55
High            57   68

In [55]:
bins = [0,50,60,70,80,90,100]
labels = ['F','D','C','B','A','S']

df['Score_Grade'] = pd.cut(df['Score_Clean'], bins=bins, labels=labels)

grade_dummies = pd.get_dummies(df['Score_Grade'], prefix='Grade')
df = pd.concat([df, grade_dummies], axis=1)

print(df['Score_Grade'].value_counts())

Score_Grade
D    79
A    78
F    73
B    73
S    70
C    66
Name: count, dtype: int64

In [56]:
final_cols = [
    'Age_Clean','Salary_Capped','Score_Clean','Experience_Clean','Tenure_Years',
    'Salary_Per_Year_Exp','Is_Senior','Exp_Age_Ratio','Age_Group_Encoded',
    'Rating_Encoded','Education_Encoded','Gender_Encoded','Loan_Encoded'
]

dept_cols = [col for col in df.columns if col.startswith('Dept_')]

df_final = df[final_cols + dept_cols]

print(df_final.isnull().sum())
print(df_final.shape)
print(df_final.head())

Age_Clean               0
Salary_Capped           0
Score_Clean            61
Experience_Clean        0
Tenure_Years            0
Salary_Per_Year_Exp     0
Is_Senior               0
Exp_Age_Ratio           0
Age_Group_Encoded       0
Rating_Encoded          0
Education_Encoded       0
Gender_Encoded          0
Loan_Encoded            0
Dept_Data Science       0
Dept_Design             0
Dept_Engineering        0
Dept_Finance            0
Dept_HR                 0
Dept_Legal              0
Dept_Marketing          0
Dept_Operations         0
Dept_Sales              0
Dept_Support            0
dtype: int64
(500, 23)
   Age_Clean  Salary_Capped  Score_Clean  Experience_Clean  Tenure_Years  \
0       56.0       163755.0         83.0              31.0           8.6
1       40.0        97043.0         68.0              16.0           3.5
2       53.0       156862.0         75.0              30.0           7.2
3       48.0       133665.0         68.0              23.0           7.1
4       28.0        35848.0         94.0               3.0           5.0

   Salary_Per_Year_Exp  Is_Senior  Exp_Age_Ratio Age_Group_Encoded  \
0              5117.34          1          0.554                 4
1              5708.41          1          0.400                 2
2              5060.06          1          0.566                 3
3              5569.38          1          0.479                 3
4              8962.00          0          0.107                 1

   Rating_Encoded  ...  Dept_Data Science  Dept_Design  Dept_Engineering  \
0               3  ...               True        False             False
1               3  ...              False        False             False
2               4  ...               True        False             False
3               2  ...              False        False             False
4               3  ...              False        False             False

   Dept_Finance  Dept_HR  Dept_Legal  Dept_Marketing  Dept_Operations  \
0         False    False       False           False            False
1         False    False       False           False            False
2         False    False       False           False            False
3         False     True       False           False            False
4         False    False       False            True            False

   Dept_Sales  Dept_Support
0       False         False
1        True         False
2       False         False
3       False         False
4       False         False

[5 rows x 23 columns]